credentials:
  usernames:
    admin-guc:
      email: admin@guc.edu.com
      name: admin
      password: $2b$12$mphwfDNFhpEwS2YE159zceTXlkxEMJR3yrD2EDVYkxa3wGV/6X57e
cookie:
  expiry_days: 30
  key: new_signature_key # Must be string
  name: cookie_name